## Clustering Grocery Items
Online shops often sell tons of different items and this can become very messy very quickly!
Data science can be extremely useful to automatically organize the products in categories so that they can be easily found by the customers.
The goal of this challenge is to look at user purchase history and create categories of items that are likely to be bought together and, therefore, should belong to the same section.

## Challenge Description
Company XYZ is an online grocery store. In the current version of the website, they have manually grouped the items into a few categories based on their experience.
However, they now have a lot of data about user purchase history. Therefore, they would like to put the data into use!
This is what they asked you to do:

### This is what they asked you to do:

-- The company founder wants to meet with some of the best customers to go through a focus group with them. 
    You are asked to send the ID of the following customers to the founder:
    
        * the customer who bought the most items overall in her lifetime for each item
        * the customer who bought that product the most
        
-- Cluster items based on user co-purchase history. That is, create clusters of products that have the highest probability of being bought together. The goal of this is to replace the old/manually created categories with these new ones. Each item can belong to just one cluster.

In [3]:
import pandas as pd

Untitled.ipynb  grocery/        grocery.zip

In [9]:
item_to_id= pd.read_csv('./grocery/item_to_id.csv')

In [10]:
purchases = pd.read_csv('./grocery/purchase_history.csv')

In [11]:
purchases

       user_id                                                 id
0       222087                                              27,26
1      1343649                                            6,47,17
2       404134                       18,12,23,22,27,43,38,20,35,1
3      1110200                                 9,23,2,20,26,47,37
4       224107  31,18,5,13,1,21,48,16,26,2,44,32,20,37,42,35,4...
5       409803                                   43,29,8,37,23,45
6      1296632                          18,15,31,11,20,32,25,6,47
7       748280                     14,43,6,20,7,42,41,28,10,22,46
8        31625                             1,43,31,37,25,32,28,35
9       987613                            27,1,3,2,11,45,10,44,15
10      560265                            10,31,25,19,2,7,15,9,23
11       60201                   26,28,13,39,27,22,48,18,16,17,32
12     1413771                           10,30,17,45,35,2,11,3,43
13      925776                                     43,38,35,28,16
14      455303                               38,15,48,43,44,10,32
15      713697                                            2,42,18
16      226213                            48,32,16,21,13,37,34,39
17      392460                                            37,38,9
18      445179                        44,37,33,39,9,43,13,8,21,48
19      176016                      39,21,16,2,13,37,48,10,6,28,5
20     1158400                                      23,43,9,40,28
21     1275545                                9,43,38,47,17,25,40
22      772450                              41,19,23,7,18,40,25,1
23     1215832                                                 41
24      386957                  13,1,29,7,10,35,17,43,46,37,18,26
25      377243                                                  2
26       76657                            25,30,40,37,23,47,32,45
27      644868                   46,25,47,39,26,12,38,9,21,13,6,1
28     1141513                                           15,23,17
29      867267                                        44,10,26,39
...        ...                                                ...
39444  1300636          46,25,40,42,27,32,47,30,31,14,22,45,38,23
39445   763285                                                 43
39446   953878                6,32,25,36,9,40,47,46,24,22,2,34,41
39447  1405771                       27,31,5,46,21,43,11,39,44,10
39448   845798                                           24,33,42
39449    20054                                   42,21,16,2,47,25
39450   876310                                      2,10,43,41,34
39451   934118                                        38,36,23,22
39452   512741                                41,42,2,45,27,32,44
39453  1373317                              16,48,1,4,26,38,25,37
39454   389222                                             9,33,1
39455   527123             29,13,10,17,18,25,40,36,46,20,28,44,45
39456  1036226                 20,34,30,47,17,19,29,21,23,38,9,44
39457   199217                                17,6,47,11,20,37,34
39458   638358                                        24,10,40,46
39459  1479453                                              22,47
39460  1184522                                                 20
39461  1398041                   38,1,24,46,33,48,8,10,44,30,40,6
39462  1330906                                            2,45,18
39463  1499087                       36,2,38,35,28,26,43,47,29,22
39464  1494796                                      38,2,44,43,46
39465   587211                        13,39,34,27,11,31,26,41,2,8
39466   755085                          18,21,17,47,6,25,20,45,19
39467   922812                                              46,35
39468  1055933                              9,43,15,3,44,45,10,41
39469   704794                                      48,42,44,10,2
39470    31237              23,21,26,27,41,9,47,43,20,40,16,24,46
39471   724925              3,39,28,4,1,43,47,27,18,25,44,10,30,2
39472   651509                           13,39,20,32,37,1,3,18,34
39473   517744                    39,40,20,3,10,42,38,43,28,25,13

[39474 rows x 2 columns]